import React, { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { ActionPlanSkeleton } from "@/components/ui/loading";
import { ActionPlanStep } from "../components/ActionPlanStep";
import { useDiscovery } from "../hooks/useDiscovery";
import { useActionPlan } from "../hooks/useActionPlan";
import { useToast } from "@/hooks/use-toast";
import { Copy, RefreshCw, ArrowLeft } from "lucide-react";

interface ActionPlanScreenProps {
  onBack: () => void;
}

export function ActionPlanScreen({ onBack }: ActionPlanScreenProps) {
  const { selectedBenefit, userQuery, planHistory } = useDiscovery();
  const generatePlanMutation = useActionPlan();
  const { toast } = useToast();
  const [generationCount, setGenerationCount] = useState(0);

  const currentPlan = planHistory[0];

  // Generate initial plan
  useEffect(() => {
    if (selectedBenefit && !currentPlan && !generatePlanMutation.isPending) {
      generatePlan();
    }
  }, [selectedBenefit, currentPlan]);

  const generatePlan = async (regenerate = false) => {
    if (!selectedBenefit || !userQuery) return;

    try {
      const seed = regenerate ? `${Date.now()}-${Math.random()}` : "default";
      await generatePlanMutation.mutateAsync({
        benefit: selectedBenefit,
        userQuery,
        seed,
      });
      
      if (regenerate) {
        setGenerationCount(prev => prev + 1);
        toast({
          title: "Plan regenerated",
          description: "Your action plan has been updated with new suggestions.",
        });
      }
    } catch (error) {
      console.error("Plan generation failed:", error);
      toast({
        title: "Generation failed",
        description: "Using a safe fallback plan.",
        variant: "destructive",
      });
    }
  };

  const copyPlanToClipboard = async () => {
    if (!currentPlan || !selectedBenefit) return;

    const planText = [
      `Action Plan for ${selectedBenefit.title}`,
      `Total estimated time: ${currentPlan.total_estimated_time}`,
      "",
      ...currentPlan.steps.map((step, index) => 
        `${index + 1}. ${step.title} (${step.estimated_time})\n   ${step.description}`
      ),
      "",
      "Generated by BeneGuide"
    ].join("\n");

    try {
      await navigator.clipboard.writeText(planText);
      toast({
        title: "Plan copied!",
        description: "Your action plan has been copied to clipboard.",
      });
    } catch (error) {
      console.error("Copy failed:", error);
      toast({
        title: "Copy failed",
        description: "Unable to copy to clipboard.",
        variant: "destructive",
      });
    }
  };

  if (!selectedBenefit) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-4">
        <div className="text-center space-y-4">
          <h2 className="text-h2 text-text-strong">No benefit selected</h2>
          <Button variant="secondary" onClick={onBack}>
            Go Back
          </Button>
        </div>
      </div>
    );
  }

  if (!currentPlan && generatePlanMutation.isPending) {
    return (
      <div className="min-h-screen bg-background py-12 px-4">
        <div className="app-container max-w-4xl space-y-8">
          <ActionPlanSkeleton />
          <p className="text-center text-text-muted" aria-live="polite">
            Creating your personalized action plan...
          </p>
        </div>
      </div>
    );
  }

  if (!currentPlan) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-4">
        <div className="text-center space-y-4">
          <h2 className="text-h2 text-text-strong">Plan generation failed</h2>
          <p className="text-text-muted">We couldn't create your action plan. Please try again.</p>
          <div className="flex gap-4 justify-center">
            <Button variant="secondary" onClick={onBack}>
              Go Back
            </Button>
            <Button variant="default" onClick={() => generatePlan()}>
              Try Again
            </Button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background py-12 px-4">
      <div className="app-container max-w-4xl space-y-8">
        {/* Header */}
        <div className="text-center space-y-4 animate-fade-in">
          <div className="space-y-2">
            <div className="flex items-center justify-center gap-3 flex-wrap">
              <h1 className="text-h1 text-brand-900 dark:text-text-strong">
                {selectedBenefit.title}
              </h1>
              <Badge variant="secondary" className="bg-brand-600/10 text-brand-700 dark:text-brand-300 border-brand-600/20">
                {selectedBenefit.category.replace("_", " ")}
              </Badge>
            </div>
            
            <p className="text-brand-700 dark:text-text-muted">
              Your 3-step action plan
            </p>
            
            <Badge variant="outline" className="bg-elev-2 text-brand-800 dark:text-text-muted border-border">
              Overall: {currentPlan.total_estimated_time}
            </Badge>
          </div>
        </div>

        {/* Action Steps with controls */}
        <div className="space-y-4 animate-slide-up" aria-live="polite">
          {/* Top controls over first card area */}
          <div className="relative pb-6">
            <div className="absolute -top-10 right-0 flex items-center gap-2">
              <Button
                variant="ghost"
                onClick={() => generatePlan(true)}
                disabled={generatePlanMutation.isPending}
                loading={generatePlanMutation.isPending}
                className="text-brand-700 dark:text-text"
                aria-label="Regenerate Plan"
              >
                <RefreshCw className="w-4 h-4" />
              </Button>
              <Button
                variant="hero"
                size="icon"
                onClick={copyPlanToClipboard}
                className="px-3 text-white"
                aria-label="Copy Plan"
              >
                <Copy className="w-4 h-4" />
              </Button>
            </div>
            <div className="absolute -top-10 left-0">
              <Button variant="ghost" onClick={onBack} className="text-brand-700 dark:text-text">
                <ArrowLeft className="w-4 h-4" />
                Back to Benefits
              </Button>
            </div>
          </div>

          {currentPlan.steps.map((step, index) => (
            <div
              key={`${step.step}-${currentPlan.seed || 'default'}`}
              className="animate-fade-in"
              style={{ animationDelay: `${index * 150}ms` }}
            >
              <ActionPlanStep step={step} />
            </div>
          ))}
        </div>

        {/* Plan History */}
        {planHistory.length > 1 && (
          <Card className="animate-fade-in border-brand-600/20 dark:border-border">
            <CardHeader>
              <CardTitle className="text-lg">Previous Versions</CardTitle>
            </CardHeader>
            <CardContent>
              <Accordion type="single" collapsible className="w-full">
                <AccordionItem value="history">
                  <AccordionTrigger className="text-sm text-text-muted hover:text-text">
                    View {planHistory.length - 1} previous version{planHistory.length - 1 !== 1 ? 's' : ''}
                  </AccordionTrigger>
                  <AccordionContent>
                    <div className="space-y-4 pt-4">
                      {planHistory.slice(1).map((historicalPlan, historyIndex) => (
                        <div key={`history-${historyIndex}`} className="space-y-3">
                          <div className="flex items-center justify-between">
                            <h4 className="text-sm font-medium text-text-muted">
                              Version {historyIndex + 2}
                            </h4>
                            <Badge variant="outline" className="text-xs">
                              {historicalPlan.total_estimated_time}
                            </Badge>
                          </div>
                          <div className="space-y-2 pl-4 border-l-2 border-border">
                            {historicalPlan.steps.map((step) => (
                              <div key={`history-${historyIndex}-step-${step.step}`} className="text-sm">
                                <div className="font-medium text-text">{step.title}</div>
                                <div className="text-text-muted text-xs">{step.description}</div>
                              </div>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </CardContent>
          </Card>
        )}

        {/* Error handling */}
        {generatePlanMutation.isError && (
          <div className="p-4 bg-danger/10 border border-danger/20 rounded-lg text-center animate-fade-in">
            <p className="text-sm text-danger mb-2">
              Something went off track. Using a safe fallback plan.
            </p>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => generatePlanMutation.reset()}
            >
              Dismiss
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}